// <auto-generated />
using AtlasBalance.API.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AtlasBalance.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512110000_HardenReleaseSecurityPermissions")]
    partial class HardenReleaseSecurityPermissions
    {
    }
}
