// <auto-generated />
using AtlasBalance.API.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AtlasBalance.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512143000_AddRevisionConceptTrigramIndex")]
    partial class AddRevisionConceptTrigramIndex
    {
    }
}
