// <auto-generated />
using System;
using System.Net;
using AtlasBalance.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlasBalance.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510120740_AddExtractoImportacionFingerprint")]
    partial class AddExtractoImportacionFingerprint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_plazo_fijo", new[] { "activo", "proximo_vencer", "vencido", "renovado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_proceso", new[] { "pending", "success", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_token_integracion", new[] { "activo", "revocado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fuente_tipo_cambio", new[] { "api", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", new[] { "admin", "gerente", "empleado_ultra", "empleado_plus", "empleado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_cuenta", new[] { "normal", "efectivo", "plazo_fijo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_proceso", new[] { "auto", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_titular", new[] { "empresa", "particular", "autonomo" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlasBalance.API.Models.AlertaDestinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("alerta_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_alerta_destinatarios");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_alerta_destinatarios_usuario_id");

                    b.HasIndex("AlertaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_alerta_destinatarios_alerta_id_usuario_id");

                    b.ToTable("ALERTA_DESTINATARIOS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.AlertaSaldo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaUltimaAlerta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_alerta");

                    b.Property<decimal>("SaldoMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("saldo_minimo");

                    b.Property<int?>("TipoTitular")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_titular");

                    b.HasKey("Id")
                        .HasName("pk_alertas_saldo");

                    b.HasIndex("CuentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_alertas_saldo_cuenta_id_unique")
                        .HasFilter("\"cuenta_id\" IS NOT NULL");

                    b.HasIndex("TipoTitular")
                        .IsUnique()
                        .HasDatabaseName("ix_alertas_saldo_tipo_titular_unique")
                        .HasFilter("\"cuenta_id\" IS NULL AND \"tipo_titular\" IS NOT NULL");

                    b.ToTable("ALERTAS_SALDO", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CeldaReferencia")
                        .HasColumnType("text")
                        .HasColumnName("celda_referencia");

                    b.Property<string>("ColumnaNombre")
                        .HasColumnType("text")
                        .HasColumnName("columna_nombre");

                    b.Property<string>("DetallesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles_json");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .HasColumnType("text")
                        .HasColumnName("entidad_tipo");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_accion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id")
                        .HasName("pk_auditorias");

                    b.HasIndex("EntidadId")
                        .HasDatabaseName("ix_auditorias_entidad_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_auditorias_timestamp");

                    b.HasIndex("TipoAccion")
                        .HasDatabaseName("ix_auditorias_tipo_accion");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_auditorias_usuario_id_timestamp");

                    b.ToTable("AUDITORIAS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.AuditoriaIntegracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CodigoRespuesta")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_respuesta");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metodo");

                    b.Property<string>("Parametros")
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros");

                    b.Property<int?>("TiempoEjecucionMs")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_ejecucion_ms");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria_integraciones");

                    b.HasIndex("CodigoRespuesta")
                        .HasDatabaseName("ix_auditoria_integraciones_codigo_respuesta");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_auditoria_integraciones_timestamp");

                    b.HasIndex("TokenId")
                        .HasDatabaseName("ix_auditoria_integraciones_token_id");

                    b.ToTable("AUDITORIA_INTEGRACIONES", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("IniciadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("iniciado_por_id");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_archivo");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_backups");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_backups_deleted_by_id");

                    b.HasIndex("IniciadoPorId")
                        .HasDatabaseName("ix_backups_iniciado_por_id");

                    b.ToTable("BACKUPS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_modificacion_id");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Clave")
                        .HasName("pk_configuracion");

                    b.HasIndex("UsuarioModificacionId")
                        .HasDatabaseName("ix_configuracion_usuario_modificacion_id");

                    b.ToTable("CONFIGURACION", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("BancoNombre")
                        .HasColumnType("text")
                        .HasColumnName("banco_nombre");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("divisa");

                    b.Property<bool>("EsEfectivo")
                        .HasColumnType("boolean")
                        .HasColumnName("es_efectivo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("FormatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formato_id");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroCuenta")
                        .HasColumnType("text")
                        .HasColumnName("numero_cuenta");

                    b.Property<int>("TipoCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cuenta");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("titular_id");

                    b.HasKey("Id")
                        .HasName("pk_cuentas");

                    b.HasIndex("Activa")
                        .HasDatabaseName("ix_cuentas_activa");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_cuentas_deleted_at");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_cuentas_deleted_by_id");

                    b.HasIndex("Divisa")
                        .HasDatabaseName("ix_cuentas_divisa");

                    b.HasIndex("EsEfectivo")
                        .HasDatabaseName("ix_cuentas_es_efectivo");

                    b.HasIndex("FormatoId")
                        .HasDatabaseName("ix_cuentas_formato_id");

                    b.HasIndex("TipoCuenta")
                        .HasDatabaseName("ix_cuentas_tipo_cuenta");

                    b.HasIndex("TitularId")
                        .HasDatabaseName("ix_cuentas_titular_id");

                    b.ToTable("CUENTAS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.DivisaActiva", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<bool>("EsBase")
                        .HasColumnType("boolean")
                        .HasColumnName("es_base");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Simbolo")
                        .HasColumnType("text")
                        .HasColumnName("simbolo");

                    b.HasKey("Codigo")
                        .HasName("pk_divisas_activas");

                    b.ToTable("DIVISAS_ACTIVAS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Exportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaExportacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_exportacion");

                    b.Property<Guid?>("IniciadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("iniciado_por_id");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("text")
                        .HasColumnName("ruta_archivo");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_exportaciones");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("ix_exportaciones_cuenta_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_exportaciones_deleted_by_id");

                    b.HasIndex("IniciadoPorId")
                        .HasDatabaseName("ix_exportaciones_iniciado_por_id");

                    b.ToTable("EXPORTACIONES", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Extracto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean")
                        .HasColumnName("checked");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid?>("CheckedById")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by_id");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text")
                        .HasColumnName("comentarios");

                    b.Property<string>("Concepto")
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_importacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("FilaNumero")
                        .HasColumnType("integer")
                        .HasColumnName("fila_numero");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flagged_at");

                    b.Property<Guid?>("FlaggedById")
                        .HasColumnType("uuid")
                        .HasColumnName("flagged_by_id");

                    b.Property<string>("FlaggedNota")
                        .HasColumnType("text")
                        .HasColumnName("flagged_nota");

                    b.Property<int?>("ImportacionFilaOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("importacion_fila_origen");

                    b.Property<string>("ImportacionFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("importacion_fingerprint");

                    b.Property<string>("ImportacionLoteHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("importacion_lote_hash");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monto");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("saldo");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_creacion_id");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_modificacion_id");

                    b.HasKey("Id")
                        .HasName("pk_extractos");

                    b.HasIndex("Checked")
                        .HasDatabaseName("ix_extractos_checked");

                    b.HasIndex("CheckedById")
                        .HasDatabaseName("ix_extractos_checked_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_extractos_deleted_by_id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_extractos_fecha");

                    b.HasIndex("Flagged")
                        .HasDatabaseName("ix_extractos_flagged");

                    b.HasIndex("FlaggedById")
                        .HasDatabaseName("ix_extractos_flagged_by_id");

                    b.HasIndex("ImportacionLoteHash")
                        .HasDatabaseName("ix_extractos_importacion_lote_hash");

                    b.HasIndex("UsuarioCreacionId")
                        .HasDatabaseName("ix_extractos_usuario_creacion_id");

                    b.HasIndex("UsuarioModificacionId")
                        .HasDatabaseName("ix_extractos_usuario_modificacion_id");

                    b.HasIndex("CuentaId", "DeletedAt")
                        .HasDatabaseName("ix_extractos_cuenta_id_deleted_at");

                    b.HasIndex("CuentaId", "Fecha")
                        .HasDatabaseName("ix_extractos_cuenta_id_fecha");

                    b.HasIndex("CuentaId", "FilaNumero")
                        .IsUnique()
                        .HasDatabaseName("ix_extractos_cuenta_id_fila_numero");

                    b.HasIndex("CuentaId", "ImportacionFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_extractos_cuenta_id_importacion_fingerprint")
                        .HasFilter("\"importacion_fingerprint\" IS NOT NULL");

                    b.ToTable("EXTRACTOS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.ExtractoColumnaExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExtractoId")
                        .HasColumnType("uuid")
                        .HasColumnName("extracto_id");

                    b.Property<string>("NombreColumna")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_columna");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_extractos_columnas_extra");

                    b.HasIndex("ExtractoId")
                        .HasDatabaseName("ix_extractos_columnas_extra_extracto_id");

                    b.HasIndex("NombreColumna")
                        .HasDatabaseName("ix_extractos_columnas_extra_nombre_columna");

                    b.ToTable("EXTRACTOS_COLUMNAS_EXTRA", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.FormatoImportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("BancoNombre")
                        .HasColumnType("text")
                        .HasColumnName("banco_nombre");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Divisa")
                        .HasColumnType("text")
                        .HasColumnName("divisa");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("MapeoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mapeo_json");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("UsuarioCreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_creador_id");

                    b.HasKey("Id")
                        .HasName("pk_formatos_importacion");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_formatos_importacion_deleted_by_id");

                    b.HasIndex("UsuarioCreadorId")
                        .HasDatabaseName("ix_formatos_importacion_usuario_creador_id");

                    b.ToTable("FORMATOS_IMPORTACION", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.IntegrationPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccesoTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acceso_tipo");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("TitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("titular_id");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_permissions");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("ix_integration_permissions_cuenta_id");

                    b.HasIndex("TitularId")
                        .HasDatabaseName("ix_integration_permissions_titular_id");

                    b.HasIndex("TokenId")
                        .HasDatabaseName("ix_integration_permissions_token_id");

                    b.ToTable("INTEGRATION_PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.IntegrationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_revocacion");

                    b.Property<DateTime?>("FechaUltimaUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_uso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<bool>("PermisoEscritura")
                        .HasColumnType("boolean")
                        .HasColumnName("permiso_escritura");

                    b.Property<bool>("PermisoLectura")
                        .HasColumnType("boolean")
                        .HasColumnName("permiso_lectura");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_creador_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_tokens");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_integration_tokens_deleted_by_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_integration_tokens_estado");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_tokens_token_hash");

                    b.HasIndex("UsuarioCreadorId")
                        .HasDatabaseName("ix_integration_tokens_usuario_creador_id");

                    b.ToTable("INTEGRATION_TOKENS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.NotificacionAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DetallesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles_json");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones_admin");

                    b.ToTable("NOTIFICACIONES_ADMIN", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.PermisoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<bool>("PuedeAgregarLineas")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_agregar_lineas");

                    b.Property<bool>("PuedeEditarLineas")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_editar_lineas");

                    b.Property<bool>("PuedeEliminarLineas")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_eliminar_lineas");

                    b.Property<bool>("PuedeImportar")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_importar");

                    b.Property<bool>("PuedeVerCuentas")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_ver_cuentas");

                    b.Property<bool>("PuedeVerDashboard")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_ver_dashboard");

                    b.Property<Guid?>("TitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("titular_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_permisos_usuario");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("ix_permisos_usuario_cuenta_id");

                    b.HasIndex("TitularId")
                        .HasDatabaseName("ix_permisos_usuario_titular_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_permisos_usuario_usuario_id");

                    b.HasIndex("UsuarioId", "CuentaId")
                        .HasDatabaseName("ix_permisos_usuario_usuario_id_cuenta_id");

                    b.ToTable("PERMISOS_USUARIO", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.PlazoFijo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<Guid?>("CuentaReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_referencia_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateOnly?>("FechaRenovacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_renovacion");

                    b.Property<DateOnly?>("FechaUltimaNotificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ultima_notificacion");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<decimal?>("InteresPrevisto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interes_previsto");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<bool>("Renovable")
                        .HasColumnType("boolean")
                        .HasColumnName("renovable");

                    b.HasKey("Id")
                        .HasName("pk_plazos_fijos");

                    b.HasIndex("CuentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_plazos_fijos_cuenta_id");

                    b.HasIndex("CuentaReferenciaId")
                        .HasDatabaseName("ix_plazos_fijos_cuenta_referencia_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_plazos_fijos_deleted_at");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_plazos_fijos_deleted_by_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_plazos_fijos_estado");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("ix_plazos_fijos_fecha_vencimiento");

                    b.ToTable("PLAZOS_FIJOS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.PreferenciaUsuarioCuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnasEditables")
                        .HasColumnType("jsonb")
                        .HasColumnName("columnas_editables");

                    b.Property<string>("ColumnasVisibles")
                        .HasColumnType("jsonb")
                        .HasColumnName("columnas_visibles");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_preferencias_usuario_cuenta");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("ix_preferencias_usuario_cuenta_cuenta_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_preferencias_usuario_cuenta_usuario_id")
                        .HasFilter("\"cuenta_id\" IS NULL");

                    b.HasIndex("UsuarioId", "CuentaId")
                        .IsUnique()
                        .HasDatabaseName("ix_preferencias_usuario_cuenta_usuario_id_cuenta_id")
                        .HasFilter("\"cuenta_id\" IS NOT NULL");

                    b.ToTable("PREFERENCIAS_USUARIO_CUENTA", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("ReemplazadoPor")
                        .HasColumnType("text")
                        .HasColumnName("reemplazado_por");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiraEn")
                        .HasDatabaseName("ix_refresh_tokens_expira_en");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("REFRESH_TOKENS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.RevisionExtractoEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("estado");

                    b.Property<Guid>("ExtractoId")
                        .HasColumnType("uuid")
                        .HasColumnName("extracto_id");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_modificacion_id");

                    b.HasKey("Id")
                        .HasName("pk_revision_extracto_estados");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_revision_extracto_estados_estado");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_revision_extracto_estados_tipo");

                    b.HasIndex("UsuarioModificacionId")
                        .HasDatabaseName("ix_revision_extracto_estados_usuario_modificacion_id");

                    b.HasIndex("ExtractoId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_revision_extracto_estados_extracto_id_tipo");

                    b.ToTable("REVISION_EXTRACTO_ESTADOS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.TipoCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DivisaDestino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("divisa_destino");

                    b.Property<string>("DivisaOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("divisa_origen");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<int>("Fuente")
                        .HasColumnType("integer")
                        .HasColumnName("fuente");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("tasa");

                    b.HasKey("Id")
                        .HasName("pk_tipos_cambio");

                    b.HasIndex("DivisaOrigen", "DivisaDestino")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_cambio_divisa_origen_divisa_destino");

                    b.ToTable("TIPOS_CAMBIO", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Titular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactoEmail")
                        .HasColumnType("text")
                        .HasColumnName("contacto_email");

                    b.Property<string>("ContactoTelefono")
                        .HasColumnType("text")
                        .HasColumnName("contacto_telefono");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Identificacion")
                        .HasColumnType("text")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_titulares");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_titulares_deleted_at");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_titulares_deleted_by_id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_titulares_nombre");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_titulares_tipo");

                    b.ToTable("TITULARES", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaUltimaLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_login");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<DateTime?>("MfaEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<long?>("MfaLastAcceptedStep")
                        .HasColumnType("bigint")
                        .HasColumnName("mfa_last_accepted_step");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PrimerLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("primer_login");

                    b.Property<bool>("PuedeUsarIa")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_usar_ia");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_usuarios_activo");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("MfaEnabled")
                        .HasDatabaseName("ix_usuarios_mfa_enabled");

                    b.HasIndex("PuedeUsarIa")
                        .HasDatabaseName("ix_usuarios_puede_usar_ia");

                    b.HasIndex("Rol")
                        .HasDatabaseName("ix_usuarios_rol");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.UsuarioEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_emails");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuario_emails_usuario_id");

                    b.ToTable("USUARIO_EMAILS", (string)null);
                });

            modelBuilder.Entity("AtlasBalance.API.Models.AlertaDestinatario", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.AlertaSaldo", null)
                        .WithMany()
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerta_destinatarios_alertas_saldo_alerta_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerta_destinatarios_usuarios_usuario_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.AlertaSaldo", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_alertas_saldo_cuentas_cuenta_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Auditoria", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditorias_usuarios_usuario_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.AuditoriaIntegracion", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.IntegrationToken", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_integraciones_integration_tokens_token_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Backup", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_backups_usuarios_deleted_by_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IniciadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_backups_usuarios_iniciado_por_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Configuracion", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_configuracion_usuarios_usuario_modificacion_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Cuenta", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cuentas_usuarios_deleted_by_id");

                    b.HasOne("AtlasBalance.API.Models.FormatoImportacion", null)
                        .WithMany()
                        .HasForeignKey("FormatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cuentas_formatos_importacion_formato_id");

                    b.HasOne("AtlasBalance.API.Models.Titular", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuentas_titulares_titular_id");

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Exportacion", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exportaciones_cuentas_cuenta_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exportaciones_usuarios_deleted_by_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IniciadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exportaciones_usuarios_iniciado_por_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Extracto", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CheckedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extractos_usuarios_checked_by_id");

                    b.HasOne("AtlasBalance.API.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_extractos_cuentas_cuenta_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extractos_usuarios_deleted_by_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("FlaggedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extractos_usuarios_flagged_by_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extractos_usuarios_usuario_creacion_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_extractos_usuarios_usuario_modificacion_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.ExtractoColumnaExtra", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Extracto", null)
                        .WithMany()
                        .HasForeignKey("ExtractoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extractos_columnas_extra_extractos_extracto_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.FormatoImportacion", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_formatos_importacion_usuarios_deleted_by_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_formatos_importacion_usuarios_usuario_creador_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.IntegrationPermission", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_integration_permissions_cuentas_cuenta_id");

                    b.HasOne("AtlasBalance.API.Models.Titular", null)
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_integration_permissions_titulares_titular_id");

                    b.HasOne("AtlasBalance.API.Models.IntegrationToken", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_permissions_integration_tokens_token_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.IntegrationToken", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_integration_tokens_usuarios_deleted_by_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integration_tokens_usuarios_usuario_creador_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.PermisoUsuario", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permisos_usuario_cuentas_cuenta_id");

                    b.HasOne("AtlasBalance.API.Models.Titular", null)
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permisos_usuario_titulares_titular_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_usuario_usuarios_usuario_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.PlazoFijo", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Cuenta", "Cuenta")
                        .WithOne()
                        .HasForeignKey("AtlasBalance.API.Models.PlazoFijo", "CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plazos_fijos_cuentas_cuenta_id");

                    b.HasOne("AtlasBalance.API.Models.Cuenta", "CuentaReferencia")
                        .WithMany()
                        .HasForeignKey("CuentaReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plazos_fijos_cuentas_cuenta_referencia_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plazos_fijos_usuarios_deleted_by_id");

                    b.Navigation("Cuenta");

                    b.Navigation("CuentaReferencia");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.PreferenciaUsuarioCuenta", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Cuenta", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_preferencias_usuario_cuenta_cuentas_cuenta_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preferencias_usuario_cuenta_usuarios_usuario_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.RefreshToken", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.RevisionExtractoEstado", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Extracto", null)
                        .WithMany()
                        .HasForeignKey("ExtractoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revision_extracto_estados_extractos_extracto_id");

                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_revision_extracto_estados_usuarios_usuario_modificacion_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.Titular", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_titulares_usuarios_deleted_by_id");
                });

            modelBuilder.Entity("AtlasBalance.API.Models.UsuarioEmail", b =>
                {
                    b.HasOne("AtlasBalance.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_emails_usuarios_usuario_id");
                });
#pragma warning restore 612, 618
        }
    }
}
