#!/bin/sh
set -eu

OWNER_PASSWORD_SQL=$(printf "%s" "$ATLAS_BALANCE_POSTGRES_OWNER_PASSWORD" | sed "s/'/''/g")
APP_PASSWORD_SQL=$(printf "%s" "$ATLAS_BALANCE_POSTGRES_APP_PASSWORD" | sed "s/'/''/g")

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'atlas_owner') THEN
        EXECUTE 'CREATE ROLE atlas_owner WITH LOGIN PASSWORD ''' || '$OWNER_PASSWORD_SQL' || ''' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';
    ELSE
        EXECUTE 'ALTER ROLE atlas_owner WITH LOGIN PASSWORD ''' || '$OWNER_PASSWORD_SQL' || ''' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
        EXECUTE 'CREATE ROLE app_user WITH LOGIN PASSWORD ''' || '$APP_PASSWORD_SQL' || ''' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';
    ELSE
        EXECUTE 'ALTER ROLE app_user WITH LOGIN PASSWORD ''' || '$APP_PASSWORD_SQL' || ''' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';
    END IF;
END
\$\$;

ALTER DATABASE atlas_balance OWNER TO atlas_owner;
ALTER SCHEMA public OWNER TO atlas_owner;
GRANT CONNECT ON DATABASE atlas_balance TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;
EOSQL
