-- Atlas Balance - Purga de datos para entrega/publicacion
-- Ejecutar solo contra una base que deba quedar sin datos operativos.
-- Requiere un usuario con permisos de propietario sobre las tablas.

\set ON_ERROR_STOP on

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

ALTER TABLE "TITULARES" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "TITULARES" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CUENTAS" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "CUENTAS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PLAZOS_FIJOS" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "PLAZOS_FIJOS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS_COLUMNAS_EXTRA" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS_COLUMNAS_EXTRA" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "REVISION_EXTRACTO_ESTADOS" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "REVISION_EXTRACTO_ESTADOS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "EXPORTACIONES" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "EXPORTACIONES" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PREFERENCIAS_USUARIO_CUENTA" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "PREFERENCIAS_USUARIO_CUENTA" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIAS" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIAS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIA_INTEGRACIONES" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIA_INTEGRACIONES" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "BACKUPS" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "BACKUPS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "NOTIFICACIONES_ADMIN" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "NOTIFICACIONES_ADMIN" DISABLE ROW LEVEL SECURITY;

-- Las tablas maestras que se conservan no pueden apuntar a usuarios que se van a borrar.
UPDATE "CONFIGURACION"
SET usuario_modificacion_id = NULL,
    fecha_modificacion = NOW()
WHERE usuario_modificacion_id IS NOT NULL;

UPDATE "FORMATOS_IMPORTACION"
SET usuario_creador_id = NULL,
    deleted_by_id = NULL
WHERE usuario_creador_id IS NOT NULL
   OR deleted_by_id IS NOT NULL;

-- Credenciales, tokens y consumo externo: todo vacio antes de entregar.
UPDATE "CONFIGURACION"
SET valor = CASE clave
    WHEN 'smtp_host' THEN ''
    WHEN 'smtp_user' THEN ''
    WHEN 'smtp_password' THEN ''
    WHEN 'smtp_from' THEN ''
    WHEN 'exchange_rate_api_key' THEN ''
    WHEN 'ai_enabled' THEN 'false'
    WHEN 'ai_model' THEN ''
    WHEN 'openrouter_api_key' THEN ''
    WHEN 'openai_api_key' THEN ''
    WHEN 'ai_usage_month_key' THEN ''
    WHEN 'ai_usage_month_cost_eur' THEN '0'
    WHEN 'ai_usage_total_cost_eur' THEN '0'
    WHEN 'ai_usage_total_requests' THEN '0'
    WHEN 'ai_usage_last_user_id' THEN ''
    WHEN 'ai_usage_last_at_utc' THEN ''
    ELSE valor
END,
    usuario_modificacion_id = NULL,
    fecha_modificacion = NOW()
WHERE clave IN (
    'smtp_host',
    'smtp_user',
    'smtp_password',
    'smtp_from',
    'exchange_rate_api_key',
    'ai_enabled',
    'ai_model',
    'openrouter_api_key',
    'openai_api_key',
    'ai_usage_month_key',
    'ai_usage_month_cost_eur',
    'ai_usage_total_cost_eur',
    'ai_usage_total_requests',
    'ai_usage_last_user_id',
    'ai_usage_last_at_utc'
);

DELETE FROM "ALERTA_DESTINATARIOS";
DELETE FROM "ALERTAS_SALDO";
DELETE FROM "AUDITORIA_INTEGRACIONES";
DELETE FROM "INTEGRATION_PERMISSIONS";
DELETE FROM "AUDITORIAS";
DELETE FROM "BACKUPS";
DELETE FROM "EXPORTACIONES";
DELETE FROM "REVISION_EXTRACTO_ESTADOS";
DELETE FROM "EXTRACTOS_COLUMNAS_EXTRA";
DELETE FROM "EXTRACTOS";
DELETE FROM "IA_USO_USUARIOS";
DELETE FROM "PERMISOS_USUARIO";
DELETE FROM "PREFERENCIAS_USUARIO_CUENTA";
DELETE FROM "PLAZOS_FIJOS";
DELETE FROM "CUENTAS";
DELETE FROM "TITULARES";
DELETE FROM "REFRESH_TOKENS";
DELETE FROM "USUARIO_EMAILS";
DELETE FROM "INTEGRATION_TOKENS";
DELETE FROM "NOTIFICACIONES_ADMIN";
DELETE FROM "USUARIOS";

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schema_name = 'hangfire'
    ) THEN
        TRUNCATE TABLE
            hangfire.aggregatedcounter,
            hangfire.counter,
            hangfire.hash,
            hangfire.job,
            hangfire.jobparameter,
            hangfire.jobqueue,
            hangfire.list,
            hangfire.lock,
            hangfire.server,
            hangfire.set,
            hangfire.state
        RESTART IDENTITY;
    END IF;
END
$$;

ALTER TABLE "TITULARES" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TITULARES" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CUENTAS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CUENTAS" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PLAZOS_FIJOS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PLAZOS_FIJOS" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS_COLUMNAS_EXTRA" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EXTRACTOS_COLUMNAS_EXTRA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "REVISION_EXTRACTO_ESTADOS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "REVISION_EXTRACTO_ESTADOS" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EXPORTACIONES" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EXPORTACIONES" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PREFERENCIAS_USUARIO_CUENTA" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PREFERENCIAS_USUARIO_CUENTA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIAS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIAS" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIA_INTEGRACIONES" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AUDITORIA_INTEGRACIONES" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BACKUPS" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BACKUPS" FORCE ROW LEVEL SECURITY;
ALTER TABLE "NOTIFICACIONES_ADMIN" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NOTIFICACIONES_ADMIN" FORCE ROW LEVEL SECURITY;

COMMIT;

SELECT tabla, filas
FROM (
    VALUES
        ('USUARIOS', (SELECT COUNT(*) FROM "USUARIOS")),
        ('TITULARES', (SELECT COUNT(*) FROM "TITULARES")),
        ('CUENTAS', (SELECT COUNT(*) FROM "CUENTAS")),
        ('EXTRACTOS', (SELECT COUNT(*) FROM "EXTRACTOS")),
        ('INTEGRATION_TOKENS', (SELECT COUNT(*) FROM "INTEGRATION_TOKENS")),
        ('REFRESH_TOKENS', (SELECT COUNT(*) FROM "REFRESH_TOKENS")),
        ('AUDITORIAS', (SELECT COUNT(*) FROM "AUDITORIAS")),
        ('IA_USO_USUARIOS', (SELECT COUNT(*) FROM "IA_USO_USUARIOS"))
) AS resultado(tabla, filas)
ORDER BY tabla;
